In [158]:
import numpy as np

In [159]:
a = np.array([1,32,3],dtype = 'int32')
b = np.array([[2,3,4,1],[2,3,4,5]],dtype = 'int32')

c = np.array(10)
c.shape
b.dtype

dtype('int32')

In [160]:
ac = a*c
ac

array([ 10, 320,  30], dtype=int32)

In [161]:
no_of_bytes = a.itemsize * a.size
print(a.nbytes)
print(no_of_bytes) #both are same

12
12


# indexing and modifying



In [162]:
a = np.array([[2,3,4,21],[23,2,7,8],[45,2,3,40]])
print(a)

[[ 2  3  4 21]
 [23  2  7  8]
 [45  2  3 40]]


In [163]:
a[2,1]

2

In [164]:
#specific rows8
a[1,]

array([23,  2,  7,  8])

In [165]:
#specific column
a[:,2]

array([4, 7, 3])

In [166]:
a[0::2,1::2]

array([[ 3, 21],
       [ 2, 40]])

In [168]:
b[0,0::2] = [22,22]
print(b)

[[22  3 22  1]
 [ 2  3  4  5]]


# three dimensions

In [177]:
t = np.array([[[1,2,3],[4,5,6]],[[1,2,4],[5,6,7]]])
print(t)

[[[1 2 3]
  [4 5 6]]

 [[1 2 4]
  [5 6 7]]]


In [186]:
t[:,:,0]

array([[1, 4],
       [1, 5]])

In [190]:
#replace

t[0,:,2] = [99,99]
t

array([[[ 1,  2, 99],
        [ 4,  5, 99]],

       [[ 1,  2,  4],
        [ 5,  6,  7]]])

# different types of arrays

In [209]:
#zeroes matrix
np.zeros((3,3,2),dtype='int16')

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]], dtype=int16)

In [210]:
#ones matrix
np.ones((3,2),dtype='int32')

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int32)

In [214]:
np.full((3,3,2),100)

array([[[100, 100],
        [100, 100],
        [100, 100]],

       [[100, 100],
        [100, 100],
        [100, 100]],

       [[100, 100],
        [100, 100],
        [100, 100]]])

In [239]:
#returns scalar value
print(np.random.randint(4,20))

#returns a matrix
print(np.random.randint(4,20,size=(3,2)))

15
[[ 9 14]
 [19  8]
 [19  4]]


In [242]:
np.identity(3,dtype='int16')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [296]:
#repeat
arr = np.array([[1,2,3],[3,4,5]])
print(arr.shape)
r = np.repeat(arr,3,axis=0)
print(r)


(2, 3)
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [3 4 5]
 [3 4 5]
 [3 4 5]]


In [259]:
#sample task
a1 = np.ones((5,5))
b1 = np.zeros((3,3))
b1[1,1] = 9
a1[1:4,1:4]= b1
print(a1)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### copy

In [265]:
a = np.array([1,2,3,4])
b = a.copy()
b[0]=100
print(a)
print(b)

[1 2 3 4]
[100   2   3   4]


In [272]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# linear algebra

In [293]:
#mat mul
a = np.array([[2,3],[2,5],[19,6]])
b = np.array([[2,3,3],[2,3,20]])
c = np.matmul(a,b)

print(c)
print(np.linalg.det(c))

[[ 10  15  66]
 [ 14  21 106]
 [ 50  75 177]]
5.435651928564778e-12


# statistics


# axis 

In [313]:
print("axis = 0 ------------------------>")
print("axis =1 ")
print("        |")
print("        |")
print("        |")
print("        |")
print("        |")
print("        |")
print("        |")
print("        V")


axis = 0 ------------------------>
axis =1 
        |
        |
        |
        |
        |
        |
        |
        V


In [314]:

print(a)

print("max")
print(np.max(a,axis=1))
print("min")
print(np.min(a,axis=0))

[[ 2  3]
 [ 2  5]
 [19  6]]
max
[ 3  5 19]
min
[2 3]


In [307]:
print(np.sum(a,axis=1))

[ 5  7 25]


In [325]:
a = np.array([[2,3,9],[22,7,23],[2,9,0]])
b = a.reshape((3,3))
print(b)

[[ 2  3  9]
 [22  7 23]
 [ 2  9  0]]


# vertical stack

In [330]:
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])

np.hstack((a,b,b,b,b)) #vstack

array([1, 2, 3, 4, 4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7, 4, 5, 6, 7])