In [42]:
import torch

In [70]:
data = [1,2,3,3]

t = torch.tensor(data)


### cannot be able to create a tensor for string objects

one_hot = torch.nn.functional.one_hot(t,num_classes=-1) #return a np.shape rows and 0-max(data) index columns

print(one_hot)

print()

d = [1,5,7,8,9]

tt = torch.tensor(d)

one = torch.nn.functional.one_hot(tt,num_classes=-1)

print(one)


tensor([[0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 1]])

tensor([[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])


# manually creating one_hot_encoding

In [107]:
import numpy as np

target = np.array(['dog', 'dog', 'cat', 'cat', 'cat', 'dog', 'dog', 
    'cat', 'cat', 'hamster', 'hamster'])

def one_hot(array):
    unique, inverse = np.unique(array, return_inverse=True)
    onehot = np.eye(unique.shape[0])[inverse] # eye similar to identity 
    return onehot

print(one_hot(target))

# unique, inverse = np.unique(target, return_inverse=True)
# print(unique)
# print()
# print(inverse)
# print()
# one = np.eye(unique.shape[0])
# print(one.shape)
# print()
# print(one)
# print()
# print(one[[1,2,1]])
# print()
# print(one[inverse].shape)


[[0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]
